site_name: ALARM Project
theme:
  name: material
  features:
    - navigation.path
  palette:
    primary: blue

extra:
  homepage: /


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - API:
    - Endpoints: api.md
    - Security: api-security.md
  - ALARM Agent:
    - Installation Guide: installation.md
    - Uninstallation Guide: uninstall.md
    - Scripts:
      - Install: agent-install.md
      - Uninstall: agent-uninstall.md
      - Heartbeat: agent-heartbeat.md
      - Fail2Ban Sync: agent-fail2ban.md
      - ALARM Sync: agent-sync.md
  - Using the Dashboard: dashboard.md
  - Development Guide: development.md

